### ISSUE TITLE
Where are the sources for the libraries in this repository?

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/apimap-plugin#5]
### Describe your use-case which is not covered by existing documentation.

There are no source jars in https://github.com/jenkinsci/apimap-plugin/tree/main/lib/io/apimap and the jars that are there do not include sources.

**Comment by msulland** [comment]
@daniel-beck The readme gives the link to the rest of the project with source code and everything. 

What I really wanted with the jars and the source code is to use the packages available at https://github.com/orgs/apimap/packages directly into the code compiled by Jenkins (this was the way I used before it was included into jenkinssci). The problem is that I haven´t found any way to do that with the limitations that Github currently has on the packages feature.

Any ideas on how I could connect the packages with the code hosted at jenkinssci? Copying things manually it´s the way to do this.

**Comment by daniel-beck** [comment]
Looks like https://github.com/orgs/apimap/packages?ecosystem=maven is it. Thanks!

> Any ideas on how I could connect the packages with the code hosted at jenkinssci? Copying things manually it´s the way to do this.

Could you publish these packages to repo1 instead of GH packages? Most generic stuff ends up hosted elsewhere, while libraries only useful to the Jenkins plugin tend to be a module of a multimodule project, and deployed to repo.j.o along with the plugin.
